## makeCacheMatrix takes a matrix and stores it into a cache hidden in subfunction 
## cacheSolve produces the inverse (if possible) from the makeCacheMatrix if not already done

## makeCacheMatrix: Matrix from the input is stored via the set subfunction into a cache.
## At the same time m is established as a test for already existing inverse.
## setinverse transfers inverse matrix and stores is for reuse. m is set for further testing.
## A list with matrix "status" is returned

makeCacheMatrix <- function(x = matrix()) {
    m <- NULL
    set <- function(y) {
        x <<- y
        m <<- NULL
    }
    get <- function() x
    setinverse <- function(solve) m <<- solve
    getinverse <- function() m
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
}


## cacheSolve requires the list generated by makeCacheMatrix.
## first m is tested for existing inverse matrix. If m !NULL stored inverse is used.
## If m=NULL inverse matrix is generated and stored into cache of makeCacheMatrix.

cacheSolve <- function(x, ...) {
    m <- x$getinverse()
    if(!is.null(m)) {
        message("getting cached data")
        return(m)
    }
    data <- x$get()
    m <- solve(data, ...)
    x$setinverse(m)
    m
        ## Return a matrix that is the inverse of 'x'
}
